---
name: Greetings

on: [pull_request_target]

jobs:
    greeting:
        runs-on: ubuntu-latest
        steps:
            - name: Greet first time contributors
              # https://github.com/actions/first-interaction
              uses: actions/first-interaction@v1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  pr-message: |
                      # Hello @${{ github.actor }}

                      **thank you for submitting your first Pull Request** üíó!

                      Before we get started, a little reminder: our team has adopted the **[Contributor Covenant Code of Conduct]**.

                      [contributor covenant code of conduct]: https://github.com/terminal-nerds/.github/blob/main/CODE_OF_CONDUCT.md

                      üìå _Please verify below that you agree to abide by its terms._

                      -   [ ] **I agree.**

                      ---

                      ## Things to note

                      1. üí° Please mark the Pull Request as a `draft` if it is not ready. List your [TODO] list, so other contributors can help you speed it up.
                      1. ü§ù If you're lost and have some questions, please see if you can find your answer in the [CONTRIBUTING] guide.

                      [todo]: #TODO
                      [contributing]: https://github.com/terminal-nerds/configs/blob/main/.github/CONTRIBUTING.md"
